---
# postgresql92のインストール
- name: install postgresql92
  yum: name={{ item }} state=latest
  with_items:
  - postgresql92-postgresql-server
  - postgresql92-postgresql-contrib
# 自動起動の設定
- name: enable postgresql92
  service: name=postgresql92-postgresql enabled=yes
# 設定済みかの確認
- name: check postgresql.conf
  command: test -f "/opt/rh/postgresql92/root/var/lib/pgsql/data/postgresql.conf"
  register: result
  ignore_errors: true
# 初期化
- name: initdb
  command: su postgres -c '/opt/rh/postgresql92/root/usr/bin/initdb --no-locale -D /opt/rh/postgresql92/root/var/lib/pgsql/data -E UTF8'
  when: result|failed
- name: config pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/opt/rh/postgresql92/root/var/lib/pgsql/data/pg_hba.conf
  when: result|failed
- name: config postgresql.conf
  copy: src=postgresql.conf dest=/opt/rh/postgresql92/root/var/lib/pgsql/data/postgresql.conf
  when: result|failed
- name: config /etc/profile.d/postgresql92.sh
  copy: src=postgresql92.sh dest=/etc/profile.d/postgresql92.sh
  when: result|failed
# サービス起動
- name: start postgresql92
  service: name=postgresql92-postgresql state=started
# postgresユーザのパスワード初期化
- name: config postgres password
  command: /opt/rh/postgresql92/root/usr/bin/psql -U postgres -c "ALTER USER postgres with unencrypted password 'postgres';"
  when: result|failed
